---
title: "Colorado Housing Data Analysis"
author: "Jared Linares"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import altair as alt
import numpy as np

from IPython.display import Markdown
from IPython.display import display
from tabulate import tabulate
```

## Introduction Question
How can analyzing sales data for homes built pre-1980s and post-1980s, and leveraging the latest data science techniques, help predict future home sales trends in Denver and lead to more informed decisions and better outcomes for real estate professionals and homeowners?

Using open data from the city of Denver, we can find the answers to these questions and more. By identifying unique characteristics and preferences of home buyers for each group, we can develop more accurate predictive models and effective marketing strategies for real estate professionals. Additionally, understanding how property values and taxes are changing over time based on sales data can help homeowners make informed decisions about buying and selling property. Leveraging the latest data science techniques, we can create a powerful machine learning model to accurately predict future home sales trends in Denver, allowing you to make more informed decisions and stay ahead of the competition as a real estate professional.

## Elevator pitch

_Analyzing sales data for homes built pre-1980s and post-1980s is essential to predicting future home sales in Denver. By identifying unique characteristics and preferences of home buyers for each group, we can develop more accurate predictive models and effective marketing strategies for real estate professionals. Additionally, understanding how property values and taxes are changing over time based on sales data can help homeowners make informed decisions about buying and selling property. Leveraging the latest data science techniques, we can create a powerful machine learning model to accurately predict future home sales trends in Denver, allowing you to make more informed decisions and stay ahead of the competition as a real estate professional._


```{python}

# chart 1: stories vs before1980
chart1 = alt.Chart(dwellings_ml_df, title="Homes w/ One Story are most likely to be built before 1980").mark_bar().encode(
    alt.X('before1980:N', title=""),
    alt.Y('count(stories)', title="Count of Homes"),
    alt.Color('before1980:N', title="Built Before 1980?"),
    alt.Column('stories')
).interactive()

# live area

chart2 = alt.Chart(dwellings_ml_df).transform_density(
    'livearea',
    as_=['livearea', 'density'],
    groupby=['before1980']
).mark_area(opacity=.5).encode(
    x="livearea",
    y="density:Q",
    color="before1980:N"
).interactive()


```

__Highlight the grand questions__

## GRAND QUESTION 1

__COPY PASTE GRAND QUESTION 1 FROM THE PROJECT HERE__

_Add details here to answer the question but `NOT` like an assignment Q&A. You need to write your answers as a consulting solution report. A Client needs to understand the answer, but also needs to understand the decisions that went into the answer (when applicable)._

_include figures in chunks and discuss your findings in the figure._

- _YOU SHOULD HAVE QUALITY WRITING THAT DESCRIBES YOUR CHARTS AND TABLES._

- _WE HIGHLY RECOMMEND [GRAMMARLY](https://grammarly.com/) TO FIX YOUR SPELLING AND GRAMMAR. WRITING TAKES TIME TO BE CLEAR. SPEND THE TIME TO PRACITCE._ 

- _YOU SHOULD HAVE QUALITY COMMENTS THAT DESCRIBES YOUR CODES. OFTEN CODEERS WORK IN TEAMS AND YOU NEED TO HAVE QUALTIY COMMENTS FOR YOUR TEAM AND YOURSELF. YOU MAY NEED TO REVISIT CODE YOU WROTE OVER A YEAR AGO, AND IF YOU DONT COMMENT IT NOW YOU WONT REMEMBER WHY YOU DID WHAT YOU DID._

```{python}
#| label: GQ1
#| code-summary: Read and format data
# Include and execute your code here


```

_include figures in chunks and discuss your findings in the figure._

```{python}
#| label: GQ1 chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here
alt.Chart(dat.head(200))\
    .encode(x="name", y="AK")\
    .mark_bar()\
    .properties(
        width=800,
        height=300
    )
```


- _PROVIDE TABLES THAT HELP ADDRESS THE GRAND QUESTIONS.

```{python}
#| label: GQ1 table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here
mydat = dat.head(1000)\
    .groupby('year')\
    .sum()\
    .reset_index()\
    .tail(10)\
    .filter(["year", "AK","AR"])

display(mydat)

```

OR 

```{python}

Markdown(mydat.to_markdown(index=False))
```


## APPENDIX A (Additional Python Code)

```python
#paste other your code from your python file (.py) here
```

Note: Non executing Python `Snippets` include (3) \`\`\` followed by (3) more \`\`\`, each on their own line. These are not single quotes, they are the key left of the number 1 key on the keyboard. The top row can include the language of code that is pasted inbetween the \`\`\`  marks. 

Note: These also work in `Slack` and it is expected they are used for any code shared in that app. No screen shots allowed.
