---
title: "Client Report - Can you predict that?"
subtitle: "Course DS 250"
author: "Jared Linares"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
    
---

_THIS `.qmd` FILE SHOULD BE USED TO WRITE YOUR REPORT.  YOU WILL NEED TO COMPILE THE REPORT INTO A `.html` DOCUMENT AND SUBMIT IT ON CANVAS._

```{python}
#| label: libraries
from matplotlib import pyplot as plt
import pandas as pd 
import altair as alt 
import numpy as np 
import altair as alt
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.calibration import LabelEncoder

from sklearn.model_selection import train_test_split
from sklearn import tree

from sklearn import metrics
from sklearn.metrics import roc_curve, auc, RocCurveDisplay
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV



from IPython.display import Markdown
from IPython.display import display
from tabulate import tabulate
```


## Elevator pitch

_This project uses machine learning techniques to predict whether a dwelling was built before 1980. By analyzing features such as living area, number of bedrooms and bathrooms, and whether the property has a basement, the model is able to accurately predict the age of a dwelling. This type of analysis can be valuable to a range of clients, such as real estate investors, city planners, and housing agencies. It can help them make informed decisions about investing in certain areas, identifying neighborhoods that may be in need of rehabilitation, and ensuring that affordable housing is available to those who need it._


```{python}


url = 'https://raw.githubusercontent.com/byuidatascience/data4dwellings/master/data-raw/dwellings_ml/dwellings_ml.csv'
dwellings_ml = pd.read_csv(url)


alt.data_transformers.disable_max_rows()
alt.data_transformers.enable('json')


```


## GRAND QUESTION 1

__Create 2-3 charts that evaluate potential relationships between the home variables and before1980.__

__A seaborn pair plot was used to examine potential relationships between home variables and the "before1980" label. Patterns or correlations can be quickly identified by plotting each variable against every other variable. This makes it possible to more easily identify significant variables that may be useful for building our classification model. The "livearea" variable appears to have multiple linear correlations with other variables such as "basement" and "numbaths", indicating that it may be an important predictor for "before1980". Additionally, the "arcstyle_ONE-STORY" variable seems to have anti-correlation with most of the other variables.__

```{python}

h_subset = dwellings_ml.filter(['livearea', 'finbsmnt', 'basement', 
    'yearbuilt', 'tasp', 'numbdrm', 'numbaths', 'before1980',
    'stories', 'yrbuilt', 'arcstyle_ONE-STORY']).sample(500)
plot = sns.pairplot(h_subset, hue = 'before1980')
plt.suptitle("Exploring Relationships between Home Variables and Year Built: A Machine Learning Approach to Predicting Pre-1980 Homes in Denver, Colorado")
plt.show()


```

_Chart 2_

```{python}


corr = h_subset.drop(columns = 'before1980').corr()

sns.heatmap(corr)

```


## GRAND QUESTION 2

__Build a classification model labeling houses as being built “before 1980” or “during or after 1980”. Your goal is to reach or exceed 90% accuracy. Explain your final model choice (algorithm, tuning parameters, etc) and describe what other models you tried.__


```{python}

X = dwellings_ml.drop(['before1980', 'parcel', 'yrbuilt'], axis=1)
y = dwellings_ml['before1980']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
                                                    random_state=24, stratify=y)

rf = RandomForestClassifier(random_state=24)


rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

```


## GRAND QUESTION 3

__Justify your classification model by discussing the most important features selected by your model. This discussion should include a chart and a description of the features.__

```{python}

df_features = pd.DataFrame(
    {'f_names': X_train.columns, 
    'f_values': rf.feature_importances_}).sort_values('f_values', ascending = False)

(alt.Chart(df_features.query('f_values > .011'))
    .encode(
        alt.X('f_values'),
        alt.Y('f_names', sort = '-x'))
    .mark_bar())

```



## GRAND QUESTION 4

__Describe the quality of your classification model using 2-3 different evaluation metrics. You also need to explain how to interpret each of the evaluation metrics you use.__

The classification report shows that the classification model has an accuracy of 0.92 and good precision, recall, and F1-score values for both classes. The precision, recall, and F1-score values for class 0 and class 1 indicate that the model has correctly identified a high percentage of samples in both classes and has a good balance between precision and recall. This would suggest that the quality of the model is high, and that it is able to accurately predict whether a dwelling was built before 1980.

```{python}
print(metrics.classification_report(y_pred, y_test))
```



```{python}

y_probs = rf.predict_proba(X_test)[:, 1]
fpr, tpr, thresholds = roc_curve(y_test, y_probs)

roc_auc = auc(fpr, tpr)

roc_display = RocCurveDisplay(fpr=fpr, tpr=tpr, roc_auc=roc_auc, estimator_name='Random Forest Classifier')
roc_display.plot()
plt.show()

```



